import "./globals.css";
import { Metadata } from "next";
import { aeonik } from "../../font"; // if you moved it into fonts.ts
import WalletConnectionProvider from "../../components/WalletConnectionProvider";
import {Toaster} from "sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${aeonik.variable}`}>
      <body className="antialiased">
        <WalletConnectionProvider>
        {children}
        </WalletConnectionProvider>
        <Toaster/>
        </body>
    </html>
  );
}
